# Generated by Django 2.0.3 on 2019-06-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190618_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='type',
        ),
    ]
